# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Padding (in pixels) around text for tabs.
# Type: Padding
c.tabs.padding = { 'bottom': 5, 'left': 5, 'right': 5, 'top': 5 }

# Page to open if :open -t/-b/-w is used without URL. Use `about:blank`
# for a blank page.
# Type: FuzzyUrl
c.url.default_page = 'https://duckduckgo.com'

# Page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://duckduckgo.com'

# Hide the window decoration.  This setting requires a restart on
# Wayland.
# Type: Bool
c.window.hide_decoration = True

black  = '#282a46'
grey   = '#44475a'
white  = '#f8f8f2'
cyan   = '#8be9fd'
green  = '#50fa7b'
orange = '#ffb86c'
pink   = '#ff79c6'
purple = '#bd93f9'
red    = '#ff5555'
yellow = '#f1fa8c'

# Text color of the completion widget. May be a single color to use for
# all columns or a list of three colors, one for each column.
# Type: List of QtColor, or QtColor
c.colors.completion.fg = purple

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = black

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = black

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = pink

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = black

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = black

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = purple

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = white

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = black

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = white

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = black

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = white

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = red

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = cyan

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = green

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = yellow

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = black

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = grey

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = black

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = grey

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = black

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = white

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = black

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = white

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = black

# Position of the tab bar.
c.tabs.position = 'bottom'

# Always restore open sites when qutebrowser is reopened.
c.auto_save.session = True

# Fonts.
font = 'curie'
size = '12pt'
size_font = '{} {}'.format(size, font)

c.fonts.completion.entry    = size_font
c.fonts.completion.category = size_font
c.fonts.debug_console       = size_font
c.fonts.downloads           = size_font
c.fonts.hints               = size_font
c.fonts.keyhint             = size_font
c.fonts.messages.error      = size_font
c.fonts.messages.info       = size_font
c.fonts.messages.warning    = size_font
c.fonts.prompts             = size_font
c.fonts.statusbar           = size_font
c.fonts.tabs                = size_font
c.fonts.monospace           = font

# Search engines.
c.url.searchengines = {
    # Default search: DuckDuckGo search.
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    # DuckDuckGo search.
    'ddg':     'https://duckduckgo.com/?q={}',
    # Wikipedia search (Nederlands).
    'w':       'https://nl.wikipedia.org/w/index.php?search={}&title=Speciaal:Zoeken',
    # Wikipedia search (English).
    'we':      'https://en.wikipedia.org/w/index.php?search={}&title=Special:Search',
    # Wikitionary search for definitions (Nederlands).
    'wikt':    'https://nl.wiktionary.org/?search={}',
    # YouTube search for videos.
    'yt':      'https://www.youtube.com/results?search_query={}',
    # Genius search for lyrics.
    'genius':  'https://genius.com/search?q={}',
    # Reddit go to subreddit.
    'r/':      'https://reddit.com/r/{}',
}

# Keybindings.
# Clear cookies on current site.
config.bind('cc', 'jseval document.cookie.split(";").forEach(function(c) {'
                  'document.cookie = c.replace(/^ +/, "").replace(/=.*/, "'
                  '=;expires=" + new Date().toUTCString() + ";path=/"); });'
                  '"Cookies cleared."')
# Close window.
config.bind('cw', 'close')
# Open private window.
config.bind('wp', 'open --private')
