#!/bin/bash
# vim:foldmethod=marker

chunkc core::plugin_dir ~/.chunkwm_plugins

chunkc core::hotload 1

# Debugging
# chunkc core::log_file  /tmp/chunkwm.log
chunkc core::log_file  stdout
chunkc core::log_level debug

# Tiling {{{
chunkc set global_desktop_mode           bsp

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5
# }}}

# Padding {{{
chunkc set global_desktop_offset_top     20
chunkc set global_desktop_offset_bottom  20
chunkc set global_desktop_offset_left    20
chunkc set global_desktop_offset_right   20
chunkc set global_desktop_offset_gap     10

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0
# }}}

# Non-global settings {{{
chunkc set 1_desktop_mode                monocle
chunkc set 1_desktop_offset_top          10
chunkc set 1_desktop_offset_bottom       10
chunkc set 1_desktop_offset_left         10
chunkc set 1_desktop_offset_right        10

chunkc set 2_desktop_mode                monocle
chunkc set 2_desktop_offset_gap          10

chunkc set 6_desktop_mode                monocle
# }}}

# Interaction settings {{{
chunkc set window_focus_cycle            monitor
chunkc set focus_follows_mouse           intrinsic
chunkc set mouse_follows_focus           1
chunkc set window_float_next             0
chunkc set window_float_center           1
chunkc set window_region_locked          1

chunkc set mouse-drag                    1
chunkc set mouse-drag mod                fn
chunkc set ffm_bypass_modifier           fn
chunkc set ffm_standby_on_float          1
# }}}

# Border settings {{{
chunkc set focused_border_width          4
chunkc set focused_border_radius         0
chunkc set focused_border_color          0xff333333
# chunkc set focused_border_color          0xffbd93f9

chunkc set focused_border_skip_floating  1

chunkc set preselect_border_width        8
chunkc set preselect_border_radius       0
chunkc set preselect_border_color        0xffebdbb2
# }}}

# chwm-sa settings {{{
chunkc set window_float_topmost          1
chunkc set window_fade_inactive          0
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.15
chunkc set window_use_cgs_move           1
# }}}

# Blur {{{
chunkc set wallpaper                     ~/Pictures/A3MuFbJ.jpg
chunkc set wallpaper_mode                fill
chunkc set wallpaper_blur                5.0
# chunkc set wallpaper_tmp_path            /tmp/
# }}}

# chunkpy {{{
chunkc set chunkpy_path   /Users/splinter/.chunkwm_plugins/chunkpy
chunkc set chunkpy_module chunkpy
# }}}

# Plugins {{{
chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load border.so
chunkc core::load chunkpy.so
# chunkc core::load blur.so
chunkc core::load purify.so
# }}}

# Program-specific settings {{{
chunkc tiling::rule --owner kitty --role AXWindow --subrole AXDialog --state tile &
chunkc tiling::rule --owner Safari --state tile --subrole AXStandardWindow &
chunkc tiling::rule --owner alacritty --state tile &
chunkc tiling::rule --owner qutebrowser --state tile &
chunkc tiling::rule --owner \"System Preferences\" --state tile &
chunkc tiling::rule --owner Finder --name Kopiëren --state float &
chunkc tiling::rule --owner Finder --name Verwijderen --state float &
# chunkc tiling::rule --owner Finder --name Info:.+ --state float &
chunkc tiling::rule --owner macfeh --state float &
chunkc tiling::rule --owner Kap --state float &
chunkc tiling::rule --owner \"IntelliJ IDEA\" --state float &
chunkc tiling::rule --owner Emacs --state tile &
chunkc tiling::rule --owner Firefox --role AXWindow &
chunkc tiling::rule --owner \"Code - Insiders\" --state tile &
chunkc tiling::rule --owner \"Visual Studio Community\" --state tile &
chunkc tiling::rule --owner Spotify --desktop 7 &
# }}}

# Start chwm-sa
# ~/scripts/chwm-sa-inject &

# For debugging / plugin development
# echo "chunkwm startup" > /dev/stderr
