"      ________ ++     ________
"     /VVVVVVVV\++++  /VVVVVVVV\
"     \VVVVVVVV/++++++\VVVVVVVV/
"      |VVVVVV|++++++++/VVVVV/'
"      |VVVVVV|++++++/VVVVV/'
"     +|VVVVVV|++++/VVVVV/'+
"   +++|VVVVVV|++/VVVVV/'+++++
" +++++|VVVVVV|/VVVVV/'+++++++++
"   +++|VVVVVVVVVVV/'+++++++++
"     +|VVVVVVVVV/'+++++++++
"      |VVVVVVV/'+++++++++
"      |VVVVV/'+++++++++
"      |VVV/'+++++++++
"      'V/'   ++++++
"               ++

set nocompatible              " be iMproved, required
filetype off                  " required
filetype plugin indent on    " required

" --------
" Vim-plug
" --------
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

" -------
" Plugins
" -------
" Easy editing
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'scrooloose/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
" Plug 'terryma/vim-multiple-cursors'
Plug 'bling/vim-airline'
Plug 'townk/vim-autoclose'
Plug 'bronson/vim-trailing-whitespace'
Plug 'easymotion/vim-easymotion'
Plug 'airblade/vim-gitgutter'
Plug 'majutsushi/tagbar', { 'on': 'TagbarToggle' }
" Plug 'terryma/vim-smooth-scroll'
" Plug 'nathanaelkane/vim-indent-guides'
" Plug 'mattn/emmet-vim'
Plug 'editorconfig/editorconfig-vim'

" Aesthetics
" Plug 'mhinz/vim-startify'
Plug 'junegunn/goyo.vim', { 'on': 'Goyo' }
Plug 'junegunn/limelight.vim', { 'on': 'Limelight' }

" Autocompletion
Plug '~/.vim/bundle/YouCompleteMe', { 'on': 'YCM' }

" Language support
Plug 'vim-syntastic/syntastic'
" C
if has('nvim')
    Plug 'arakashic/chromatica.nvim'
endif
" Objective-C / Cocoa
Plug 'msanders/cocoa.vim'
" Rust
Plug 'rust-lang/rust.vim', { 'for': 'rust' }
Plug 'racer-rust/vim-racer', { 'for': 'rust' }
Plug 'sebastianmarkow/deoplete-rust', { 'for': 'rust' }
Plug 'cespare/vim-toml', { 'for': 'toml' }
" (La)TeX
Plug 'lervag/vimtex', { 'for': ['tex', 'plaintex'] }
" Plug 'LaTeX-Box-Team/LaTeX-Box'
" Haskell
Plug 'neovimhaskell/haskell-vim', { 'for': 'haskell' }
" JavaScript
Plug 'pangloss/vim-javascript', { 'for': 'javascript' }
Plug 'kchmck/vim-coffee-script', { 'for': 'coffee' }
" Go
Plug 'fatih/vim-go', { 'for': 'go' }

" Linters
" Plug 'sindresorhus/vim-xo'
" Plug 'prettier/prettier'

" Colour theme
" Plug 'ayu-theme/ayu-vim'
Plug 'morhetz/gruvbox'
" Plug 'junegunn/seoul256.vim'
if has('nvim')
    Plug 'vim-scripts/AfterColors.vim'
endif
" Plug 'flazz/vim-colorschemes'
" Plug 'chriskempson/base16-vim'
" Plug 'nanotech/jellybeans.vim', { 'tag': 'v1.6' }
" Plug 'arcticicestudio/nord-vim'
" Plug 'lilydjwg/colorizer'
" Plug 'dylanaraps/wal.vim'


" All of your Plugs must be added before the following line
call plug#end()

let base16colorspace=256    " Access colors present in 256 colorspace
let t_Co = 256              " Use 256 colors in terminal

" -------
" Keymaps
" -------
nmap <F8> :TagbarToggle<CR>
nmap <F7> :NERDTreeToggle<CR>

" --------------------
" NERDCommenter config
" --------------------
let g:NERDSpaceDelims = 1
let g:NERDCompactSexyComs = 1
let g:NERDDefaultAlign = 'left'
let g:NERDCommentEmptyLines = 1
let g:NERDTrimTrailingWhitespace = 1

" -------------
" Tagbar config
" -------------
let g:tagbar_type_rust = {
    \ 'ctagstype' : 'rust',
    \ 'kinds' : [
        \'T:types,type definitions',
        \'f:functions,function definitions',
        \'g:enum,enumeration names',
        \'s:structure names',
        \'m:modules,module names',
        \'c:consts,static constants',
        \'t:traits',
        \'i:impls,trait implementations',
    \]
\}
let g:tagbar_type_objc = {
    \ 'ctagstype' : 'ObjectiveC',
    \ 'kinds'     : [
        \ 'i:interface',
        \ 'I:implementation',
        \ 'p:Protocol',
        \ 'm:Object_method',
        \ 'c:Class_method',
        \ 'v:Global_variable',
        \ 'F:Object field',
        \ 'f:function',
        \ 'p:property',
        \ 't:type_alias',
        \ 's:type_structure',
        \ 'e:enumeration',
        \ 'M:preprocessor_macro',
    \ ],
    \ 'sro'        : ' ',
    \ 'kind2scope' : {
        \ 'i' : 'interface',
        \ 'I' : 'implementation',
        \ 'p' : 'Protocol',
        \ 's' : 'type_structure',
        \ 'e' : 'enumeration'
    \ },
    \ 'scope2kind' : {
        \ 'interface'      : 'i',
        \ 'implementation' : 'I',
        \ 'Protocol'       : 'p',
        \ 'type_structure' : 's',
        \ 'enumeration'    : 'e'
    \ }
\ }
let g:tagbar_type_markdown = {
    \ 'ctagstype' : 'markdown',
    \ 'kinds' : [
        \ 'h:Heading_L1',
        \ 'i:Heading_L2',
        \ 'k:Heading_L3'
    \ ]
\ }

" --------------
" Airline config
" --------------
let g:airline_detect_modified=1
let g:airline_powerline_fonts=1

" ------------------
" Multicursor config
" ------------------
" let g:multi_cursor_next_key='<C-d>'

" ------------
" Racer config
" ------------
set hidden
let g:racer_cmd = "/Users/splinter/.cargo/bin/racer"
let g:racer_experimental_completer = 1
au FileType rust nmap gd <Plug>(rust-def)
au FileType rust nmap gs <Plug>(rust-def-split)
au FileType rust nmap gx <Plug>(rust-def-vertical)
au FileType rust nmap <leader>gd <Plug>(rust-doc)

" -----------------
" Chromatica config
" -----------------
let g:chromatica#libclang_path='/usr/local/opt/llvm/lib'
let g:chromatica#enable_at_startup=1

" -----------
" Rust config
" -----------
let g:rustfmt_autosave = 1
let g:syntastic_rust_checkers = ['cargo']

" ----------------
" Syntastic config
" ----------------
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" --------------------
" Deoplete Rust config
" --------------------
let g:deoplete#sources#rust#racer_binary='/Users/splinter/.cargo/bin/racer'
let g:deoplete#sources#rust#rust_source_path='/Users/splinter/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src'

" --------------------
" YouCompleteMe config
" --------------------
let g:ycm_auto_trigger=0

" ---------------
" Startify config
" ---------------
let g:startify_bookmarks = ['~/.vimrc', '~/.zshrc', '~/dotfiles']
" let g:startify_custom_header = map(split(system('figlet -f slant neovim'), '\n'), '"   ". v:val') + ['','']
" The vim logo taken from this file.
let g:startify_custom_header = map(split(system('sed -n 1,15p ~/.vimrc | cut -c 3-'), '\n'), '"    " . v:val') + ['','']

" -------------
" Smooth scroll
" -------------
" noremap <silent> <c-u> :call smooth_scroll#up(&scroll, 0, 2)<CR>
" noremap <silent> <c-d> :call smooth_scroll#down(&scroll, 0, 2)<CR>
" noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 0, 4)<CR>
" noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 0, 4)<CR>

" Make sure guicolors are used when available
if has("termguicolors")
    set termguicolors
endif

" Tab settings
set tabstop=4
set softtabstop=4 expandtab
set shiftwidth=4

" Syntax settings
syntax on
filetype plugin indent on
filetype plugin on
colo gruvbox
let g:gruvbox_contrast_dark='hard'
set background=dark
let t_ZH="^[[3m"
let t_ZR="^[[23m"
let g:limelight_conceal_ctermfg = 'gray'
" let g:limelight_conceal_guifg = 'DarkGray'

" Line number settings
set cul
set number
set relativenumber
set numberwidth=3

" Scroll settings
" set so=3

" Mouse settings
set mouse=nv " Normal and Visual

" Wrap settings
set wrap lbr
" set nowrap
noremap  <buffer> <silent> k gk
noremap  <buffer> <silent> j gj
noremap  <buffer> <silent> 0 g0
noremap  <buffer> <silent> $ g$<Paste>

" NOTE: The § is just below esc, and is easier to reach.
inoremap § <Esc>

if has('nvim')
    tnoremap <Esc> <c-\><c-n>
    inoremap <Esc> <Esc><Esc>
endif

let g:python_host_prog = "/usr/local/bin/python2.7"
let g:python3_host_prog = "/usr/local/bin/python3"

" Reload khd config on write.
au BufWritePost .khdrc !khd -e reload

