fpath+=~/.zfunc

autoload -Uz compinit
compinit

HISTSIZE=1000
SAVEHIST=1000
HYPHEN_INSENSITIVE="true"

### Antigen {{{
source ~/dotfiles/zsh/antigen/antigen.zsh

antigen use oh-my-zsh antigen bundle git
# antigen bundle ruby
antigen bundle golang
antigen bundle node
antigen bundle python
antigen bundle osx

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions

antigen bundle wookayin/anybar-zsh

# antigen theme robbyrussell
# antigen theme sobolevn/sobole-zsh-theme
# antigen theme sorin
# antigen theme denysdovhan/spaceship-zsh-theme spaceship

antigen apply
### }}}

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern root line)
# Don't underline paths (!)
ZSH_HIGHLIGHT_STYLES[path]='fg=white'

local ret_status="%(?:%{$fg_bold[green]%}:%{$fg_bold[red]%})"
#      Blue fg                  Italic on           Cyan foreground    CWD Reset fg      Italic off          Ret status
PS1="%{$fg_bold[blue]%}Splinter $(echo -e '\e[3m')%{$fg_no_bold[cyan]%}%c%{$reset_color%}$(echo -e '\e[23m') ${ret_status}:: "

ZSH_THEME_GIT_PROMPT_PREFIX="%{$fg[red]%}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%} "
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[yellow]%}✗"
ZSH_THEME_GIT_PROMPT_CLEAN=" "

# RPS1='$(git_prompt_info)%{$fg[blue]%}%T%{$reset_color%}'
RPS1='$(git_prompt_info)%{$reset_color%}'

# Python {{{
alias setpython3path="unset PYTHONPATH && export PYTHONPATH=/usr/local/lib/python3.6/site-packages/"
alias setpython2path="unset PYTHONPATH && export PYTHONPATH=/usr/local/lib/python2.7/site-packages/"
unset PYTHONPATH
# }}}

# Terminal title theme {{{
export ZSH_THEME_TERM_TITLE_IDLE="%~"
export ZSH_THEME_TERM_TAB_TITLE_IDLE="%~"
# }}}

# Lang {{{
export LC_ALL="en_GB.UTF-8"
export LANG=en_GB.UTF-8
# }}}

# Editors {{{
export EDITOR=nvim
export VISUAL=nvim
# }}}

# Aliases {{{
alias zshrc="vi ~/.zshrc"
# alias ls="ls -Gp"
alias v="nvim"
alias vi="nvim"
# alias vim="nvim"
alias scrot="screencapture -t png"
alias cr="cargo run"
alias cb="cargo build"
alias fuck="sudo !!"
alias watch1="watch -t -d -n 1"
alias love="open -na love"
alias code="code-insiders"
alias :q="exit"
alias ls="exa -GF"
# }}}

# Functions {{{
ip () {
  echo "Public ip: $(curl -4fNs ipinfo.io/ip)"
  echo "Local ip: $(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')"
}
texpreview () {
  # Open the pdf file in Skim.
  # Skim auto-reloads (after enabling it) the pdf file after build.
  open -a "Skim" "$@"
}
function macfeh () {
  open -b "drabweb.macfeh" "$@"
}
# }}}

if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi

# Paths {{{
export RUST_SRC_PATH=/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/src
export GOPATH=~/.go
export PATH=$PATH:~/scripts:~/.swiftenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:~/.swiftenv/shims:~/.miniconda3/bin:/Users/splinter/.cargo/bin:/Library/TeX/texbin/:~/.local/bin:/Applications/kitty.app/Contents/MacOS
# }}}
