# Spaceship settings
SPACESHIP_PROMPT_SYMBOL=➜
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=true
SPACESHIP_PROMPT_PREFIXES_SHOW=true
SPACESHIP_PROMPT_SUFFIXES_SHOW=true
SPACESHIP_PROMPT_DEFAULT_PREFIX="via "

HISTSIZE=1000
SAVEHIST=1000
HYPHEN_INSENSITIVE="true"

### Antigen {{{
source ~/dotfiles/zsh/antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
# antigen bundle ruby
# antigen bundle golang
antigen bundle node
antigen bundle python
antigen bundle osx

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions

# antigen theme robbyrussell
# antigen theme
antigen theme denysdovhan/spaceship-zsh-theme spaceship

antigen apply
### }}}

### User configuration

# Python {{{
# okay, this works, but it is probably very ugly, but I'm happy
alias setpython3path="unset PYTHONPATH && export PYTHONPATH=/usr/local/lib/python3.6/site-packages/"
alias setpython2path="unset PYTHONPATH && export PYTHONPATH=/usr/local/lib/python2.7/site-packages/"
unset PYTHONPATH
# }}}

# Terminal title theme {{{
export ZSH_THEME_TERM_TITLE_IDLE="%~"
export ZSH_THEME_TERM_TAB_TITLE_IDLE="%~"
# }}}

# Lang {{{
export LC_ALL="nl_NL"
export LANG=nl_NL.UTF-8
# }}}

# kwm {{{
alias kwm="brew services restart kwm"
# }}}

# Aliases {{{
alias zshrc="vi ~/.zshrc"
ip () {
  echo "Public ip: $(curl -s https://4.ifcfg.me/)"
  echo "Local ip: $(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')"
}
alias ls="ls -Gp"
alias vi="nvim"
alias vim="nvim"
# }}}

if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi

# Paths {{{
export GOPATH=~/code/go
export PATH=~/.swiftenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:~/.swiftenv/shims:~/.miniconda3/bin
# }}}
