{ ... }: {
  imports = [
    ../../configuration/home.nix

    ./home/polybar.nix

    ../../configuration/home/agda.nix
    ../../configuration/home/audio.nix
    ../../configuration/home/browser.nix
    ../../configuration/home/c.nix
    ../../configuration/home/chat.nix
    ../../configuration/home/direnv.nix
    ../../configuration/home/dunst.nix
    ../../configuration/home/emacs.nix
    ../../configuration/home/feh.nix
    ../../configuration/home/fonts.nix
    ../../configuration/home/games.nix
    ../../configuration/home/git.nix
    ../../configuration/home/gpg.nix
    ../../configuration/home/gtk.nix
    ../../configuration/home/haskell.nix
    ../../configuration/home/hledger.nix
    ../../configuration/home/home-manager.nix
    ../../configuration/home/htop.nix
    ../../configuration/home/keyboard.nix
    ../../configuration/home/language.nix
    ../../configuration/home/lorri.nix
    ../../configuration/home/mail.nix
    ../../configuration/home/markdown.nix
    ../../configuration/home/misc.nix
    ../../configuration/home/mopidy.nix
    ../../configuration/home/mpdscribble.nix
    ../../configuration/home/mpv.nix
    ../../configuration/home/ncmpcpp.nix
    ../../configuration/home/newsboat.nix
    ../../configuration/home/nix.nix
    ../../configuration/home/onedrive.nix
    ../../configuration/home/org-mode.nix
    ../../configuration/home/pass.nix
    ../../configuration/home/polybar.nix
    ../../configuration/home/python.nix
    ../../configuration/home/redshift.nix
    ../../configuration/home/rust.nix
    ../../configuration/home/scheme.nix
    ../../configuration/home/shell.nix
    ../../configuration/home/ssh.nix
    ../../configuration/home/tex.nix
    ../../configuration/home/theme.nix
    ../../configuration/home/tmux.nix
    ../../configuration/home/tools.nix
    ../../configuration/home/unclutter.nix
    ../../configuration/home/urxvt.nix
    ../../configuration/home/xdg.nix
    ../../configuration/home/xresources.nix
    ../../configuration/home/xsession.nix
    ../../configuration/home/yaml.nix
    ../../configuration/home/zathura.nix
  ];
}
